const photos = {
  hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1800&q=85",
  dhow: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=82",
  ocean: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=82",
  sunset: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=82",
  mangrove: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1000&q=82",
  midaCreek: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Watamu_Mida_Creek_6.jpg",
  ruins: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1000&q=82",
  beach: "https://images.unsplash.com/photo-1540202404-a2f29016b523?auto=format&fit=crop&w=1000&q=82",
  dining: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=82",
  night: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=82",
  family: "https://images.unsplash.com/photo-1504150558240-0b4fd8946624?auto=format&fit=crop&w=1000&q=82",
};

export const navItems = [
  { label: "Explore", path: "/things-to-do" },
  { label: "Stay", path: "/places-to-stay" },
  { label: "Eat & Drink", path: "/eat-and-drink" },
  { label: "Nightlife", path: "/nightlife" },
  { label: "Transfers", path: "/transfers" },
  { label: "Places to Visit", path: "/places-to-visit" },
  { label: "Itineraries", path: "/itineraries" },
  { label: "What's On", path: "/whats-on" },
];

export const exploreCategories = [
  { title: "Things to Do", text: "Marine experiences, adventure, nature and culture.", path: "/things-to-do", image: photos.ocean, tone: "teal" },
  { title: "Where to Stay", text: "Hotels, resorts, villas, apartments and guesthouses.", path: "/places-to-stay", image: photos.beach, tone: "sand" },
  { title: "Eat & Drink", text: "Restaurants, cafés, beach dining and bars.", path: "/eat-and-drink", image: photos.dining, tone: "coral" },
  { title: "Nightlife", text: "Clubs, lounges, DJs, live music and beach parties.", path: "/nightlife", image: photos.night, tone: "ink" },
  { title: "Transfers", text: "Airport, SGR, Mombasa, Watamu and private transport.", path: "/transfers", image: photos.dhow, tone: "sky" },
  { title: "Places to Visit", text: "Beaches, history, nature and attractions.", path: "/places-to-visit", image: photos.ruins, tone: "olive" },
];

const experienceEntries = [
  {
    id: "malindi-marine-national-park",
    slug: "malindi-marine-national-park",
    name: "Malindi Marine National Park",
    category: "Marine",
    location: "Malindi",
    duration: "Half day",
    image: photos.ocean,
    description: "A marine destination for time on the water, reef experiences and a different view of Malindi's coast. Ask Visit Malindi about current ways to experience it.",
    highlights: ["Indian Ocean", "Marine experiences", "Boat and water options"],
    featured: true,
  },
  {
    id: "watamu-marine-national-park",
    slug: "watamu-marine-national-park",
    name: "Watamu Marine National Park",
    category: "Marine",
    location: "Watamu",
    duration: "Ask for options",
    image: photos.ocean,
    description: "Explore the Watamu side of the coast through marine experiences shaped around your time, group and interests.",
    highlights: ["Watamu coast", "Marine experiences", "Flexible trip planning"],
    featured: true,
  },
  {
    id: "mida-creek-sunset",
    slug: "mida-creek-sunset",
    name: "Mida Creek",
    category: "Nature",
    location: "Mida Creek",
    duration: "Sunset",
    image: photos.midaCreek,
    description: "Slow down among mangroves and wide tidal horizons. Ask about current ways to experience Mida Creek from Watamu.",
    highlights: ["Mangrove waterways", "Golden-hour views", "Nature and local culture"],
    featured: true,
  },
  {
    id: "gede-ruins",
    slug: "gede-ruins",
    name: "Gede Ruins",
    category: "History & Culture",
    location: "Gede",
    duration: "Half day",
    image: photos.ruins,
    description: "Walk through the atmospheric remains of a historic Swahili settlement surrounded by coastal forest.",
    highlights: ["Swahili heritage", "Forest setting", "History"],
    featured: true,
  },
  {
    id: "dhow-sailing",
    slug: "dhow-sailing",
    name: "Dhow Sailing",
    category: "Marine",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.dhow,
    description: "See the coastline from the water aboard a traditional dhow. Visit Malindi can help you find the right experience for your day.",
    highlights: ["Traditional dhow", "Ocean views", "Sunset possibilities"],
    tags: ["Boat Trips"],
    featured: true,
  },
  {
    id: "turtle-experiences",
    slug: "turtle-related-experiences",
    name: "Turtle-related experiences",
    category: "Nature",
    location: "Watamu",
    duration: "Ask for options",
    image: photos.ocean,
    description: "Ask Visit Malindi about responsible turtle-related experiences and the best current way to include them in your coast plans.",
    highlights: ["Watamu", "Nature-led experiences", "Responsible travel guidance"],
    featured: false,
  },
  {
    id: "snorkelling",
    slug: "snorkelling-on-the-coast",
    name: "Snorkelling on the coast",
    category: "Snorkelling",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.ocean,
    description: "A simple way to spend time in the water. Ask Visit Malindi about current snorkelling options and the best fit for your day.",
    highlights: ["Marine life", "Time on the water", "Malindi and Watamu options"],
    featured: false,
  },
  {
    id: "diving",
    slug: "diving-on-the-coast",
    name: "Diving on the coast",
    category: "Diving",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.ocean,
    description: "For visitors looking to explore below the surface, with local guidance on current diving possibilities.",
    highlights: ["Underwater experiences", "Marine environments", "Local guidance"],
    featured: false,
  },
  {
    id: "dolphin-experiences",
    slug: "dolphin-experiences",
    name: "Dolphin experiences",
    category: "Dolphin Experiences",
    location: "Watamu",
    duration: "Ask for options",
    image: photos.ocean,
    description: "Ask about responsible dolphin-related experiences and current conditions before making plans.",
    highlights: ["Watamu", "Marine wildlife", "Responsible planning"],
    featured: false,
  },
  {
    id: "sunset-cruises",
    slug: "sunset-cruises",
    name: "Sunset cruises",
    category: "Sunset Cruises",
    location: "Malindi & Watamu",
    duration: "Sunset",
    image: photos.sunset,
    description: "Finish the day on the water. Visit Malindi can help you ask about current sunset cruise options.",
    highlights: ["Golden hour", "Ocean views", "A slower evening"],
    featured: false,
  },
  {
    id: "sandbank-experiences",
    slug: "sandbank-experiences",
    name: "Sandbank experiences",
    category: "Sandbank",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.ocean,
    description: "A bright, open-water way to spend part of a coast day. Ask about tides, timing and current options.",
    highlights: ["Open water", "Flexible timing", "Marine setting"],
    featured: false,
  },
  {
    id: "water-sports",
    slug: "water-sports",
    name: "Water sports",
    category: "Water Sports",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.beach,
    description: "Explore water-based activities at a pace that suits your group, with current options confirmed through the concierge.",
    highlights: ["Active coast days", "Water-based fun", "Flexible enquiries"],
    featured: false,
  },
  {
    id: "beach-activities",
    slug: "beach-activities",
    name: "Beach activities",
    category: "Beach Activities",
    location: "Malindi & Watamu",
    duration: "Flexible",
    image: photos.beach,
    description: "Keep it simple with a beach-led day, from a quiet shoreline to easy activities for friends or family.",
    highlights: ["Beach time", "Families and groups", "Flexible pace"],
    featured: false,
  },
  {
    id: "wildlife-coast",
    slug: "wildlife-on-the-coast",
    name: "Wildlife on the coast",
    category: "Wildlife",
    location: "Wider Coast",
    duration: "Ask for options",
    image: photos.mangrove,
    description: "Add nature and wildlife to your coast plans with local guidance on suitable destinations and current arrangements.",
    highlights: ["Nature-led travel", "Wider Coast", "Local context"],
    featured: false,
  },
  {
    id: "family-coast-day",
    slug: "family-coast-day",
    name: "Family coast day",
    category: "Family Activities",
    location: "Malindi & Watamu",
    duration: "Flexible",
    image: photos.family,
    description: "A flexible starting point for families who want beach time, gentle discovery and room to follow the day.",
    highlights: ["Family-friendly planning", "Flexible pace", "Beach and nature"],
    featured: false,
  },
  {
    id: "couples-coast-day",
    slug: "couples-coast-day",
    name: "Couples coast day",
    category: "Couples & Romantic",
    location: "Malindi & Watamu",
    duration: "Flexible",
    image: photos.sunset,
    description: "Shape a slower day for two around the ocean, a good meal and a memorable evening.",
    highlights: ["For two", "Sunset possibilities", "Unhurried planning"],
    featured: false,
  },
  {
    id: "coast-photography",
    slug: "coast-photography",
    name: "Coast photography",
    category: "Photography",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.sunset,
    description: "Find light, texture and coastal detail with suggestions for shaping a photography-led day.",
    highlights: ["Coastal light", "Landscape and culture", "Flexible route"],
    featured: false,
  },
  {
    id: "wellness-relaxation",
    slug: "wellness-and-relaxation",
    name: "Wellness and relaxation",
    category: "Wellness",
    location: "Malindi & Watamu",
    duration: "Flexible",
    image: photos.beach,
    description: "Leave space for slower mornings, beach time and a gentler rhythm on the coast.",
    highlights: ["Slow travel", "Rest and reset", "Flexible planning"],
    featured: false,
  },
  {
    id: "horse-riding",
    slug: "horse-riding",
    name: "Horse Riding by the Coast",
    category: "Adventure",
    location: "Malindi area",
    duration: "Ask for options",
    image: photos.beach,
    description: "An unhurried coastal adventure for riders looking for a memorable way to explore the landscape.",
    highlights: ["Outdoor adventure", "Coastal scenery", "Flexible enquiry"],
    featured: false,
  },
  {
    id: "deep-sea-fishing",
    slug: "deep-sea-fishing",
    name: "Deep Sea Fishing",
    category: "Adventure",
    location: "Malindi",
    duration: "Ask for options",
    image: photos.ocean,
    description: "Ask about deep sea fishing options, current conditions and suitable trips for your group.",
    highlights: ["Open water", "Private enquiries", "Local guidance"],
    tags: ["Fishing"],
    featured: false,
  },
  {
    id: "glass-bottom-boat",
    slug: "glass-bottom-boat-experiences",
    name: "Glass-bottom boat experiences",
    category: "Boat Trips",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.ocean,
    description: "See more of the coast from the water with a route shaped around your interests. Ask about current options and conditions.",
    highlights: ["Water-level views", "Marine setting", "Flexible group planning"],
    tags: ["Marine", "Family"],
    featured: false,
  },
  {
    id: "coastal-boat-trips",
    slug: "coastal-boat-trips",
    name: "Coastal boat trips",
    category: "Boat Trips",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.dhow,
    description: "A coast-day starting point for visitors who want to get out on the Indian Ocean and shape the route around their interests.",
    highlights: ["Indian Ocean", "Flexible routes", "Malindi and Watamu options"],
    tags: ["Marine", "Adventure"],
    featured: false,
  },
  {
    id: "coastal-fishing-trips",
    slug: "coastal-fishing-trips",
    name: "Coastal fishing trips",
    category: "Fishing",
    location: "Malindi & Watamu",
    duration: "Ask for options",
    image: photos.ocean,
    description: "For visitors interested in a fishing-led coast day, with current options, conditions and group fit confirmed through the concierge.",
    highlights: ["Time on the water", "Flexible enquiries", "Coast planning"],
    tags: ["Marine", "Adventure"],
    featured: false,
  },
  {
    id: "nature-walks",
    slug: "nature-walks-on-the-coast",
    name: "Nature walks on the coast",
    category: "Nature",
    location: "Wider Coast",
    duration: "Ask for options",
    image: photos.mangrove,
    description: "Step away from the shoreline for a slower nature-led experience around coastal forest, creek or river landscapes.",
    highlights: ["Coastal landscapes", "Flexible pace", "Nature-led planning"],
    tags: ["Nature", "Relaxation", "Photography"],
    featured: false,
  },
  {
    id: "bird-watching",
    slug: "bird-watching-on-the-coast",
    name: "Bird watching on the coast",
    category: "Nature",
    location: "Mida Creek",
    duration: "Ask for options",
    image: photos.midaCreek,
    description: "Build a quiet coast day around the creek and wider natural environment, with current guidance on the best way to include bird watching.",
    highlights: ["Mida Creek", "Nature observation", "Slow travel"],
    tags: ["Nature", "Photography", "Relaxation"],
    featured: false,
  },
  {
    id: "coastal-culture-walks",
    slug: "coastal-culture-walks",
    name: "Coastal culture walks",
    category: "History & Culture",
    location: "Malindi",
    duration: "Flexible",
    image: photos.ruins,
    description: "Link Malindi's old-town atmosphere, waterfront landmarks and coastal history in a slower, context-led day.",
    highlights: ["Malindi history", "Coastal culture", "Flexible route"],
    tags: ["Culture", "Photography", "Family"],
    featured: false,
  },
];

const excursionEntries = [
  {
    id: "malindi-coast-excursion",
    slug: "malindi-coast-excursion",
    name: "Malindi coast excursion",
    category: "Day Trip",
    location: "Malindi",
    duration: "Flexible",
    image: photos.beach,
    description: "A flexible day around Malindi's beaches, waterfront and cultural places, shaped around your interests.",
    highlights: ["Malindi", "Beach and culture", "Flexible planning"],
    featured: true,
  },
  {
    id: "watamu-mida-creek-excursion",
    slug: "watamu-and-mida-creek",
    name: "Watamu and Mida Creek",
    category: "Nature",
    location: "Watamu",
    duration: "Day Trip",
    image: photos.midaCreek,
    description: "Combine Watamu's coast with time around Mida Creek. Ask about current travel options and timing.",
    highlights: ["Watamu", "Mida Creek", "Nature-led day"],
    featured: true,
  },
  {
    id: "gede-arabuko-excursion",
    slug: "gede-and-arabuko-sokoke",
    name: "Gede and Arabuko Sokoke",
    category: "Culture & Nature",
    location: "Gede",
    duration: "Day Trip",
    image: photos.ruins,
    description: "A culture-and-nature route pairing Gede's historic setting with the surrounding coastal forest region.",
    highlights: ["Gede", "History", "Coastal forest"],
    featured: true,
  },
  {
    id: "mambrui-excursion",
    slug: "mambrui-excursion",
    name: "Mambrui excursion",
    category: "Culture",
    location: "Mambrui",
    duration: "Day Trip",
    image: photos.beach,
    description: "A wider-coast outing for travellers who want to explore beyond Malindi at an unhurried pace.",
    highlights: ["Mambrui", "Wider Coast", "Flexible route"],
    featured: false,
  },
  {
    id: "kilifi-excursion",
    slug: "kilifi-excursion",
    name: "Kilifi excursion",
    category: "Day Trip",
    location: "Kilifi",
    duration: "Day Trip",
    image: photos.ocean,
    description: "Consider Kilifi as a wider-coast day trip when shaping a route between the region's coastal destinations.",
    highlights: ["Kilifi", "Wider Coast", "Route planning"],
    featured: false,
  },
  {
    id: "marafa-excursion",
    slug: "marafa-hells-kitchen",
    name: "Marafa / Hell's Kitchen",
    category: "Adventure",
    location: "Marafa",
    duration: "Day Trip",
    image: photos.ruins,
    description: "A change of scenery inland from the coast. Ask Visit Malindi about current travel options and how to plan the day.",
    highlights: ["Marafa", "Landscape", "Inland day trip"],
    featured: false,
  },
  {
    id: "mombasa-excursion",
    slug: "mombasa-day-trip",
    name: "Mombasa day trip",
    category: "Day Trip",
    location: "Mombasa",
    duration: "Day Trip",
    image: photos.dhow,
    description: "Build a Mombasa day into a wider coast itinerary with local help on timing and transport.",
    highlights: ["Mombasa", "Wider Coast", "Flexible itinerary"],
    featured: false,
  },
  {
    id: "tsavo-excursion",
    slug: "tsavo-coast-extension",
    name: "Tsavo coast extension",
    category: "Wildlife",
    location: "Tsavo",
    duration: "Flexible",
    image: photos.mangrove,
    description: "For travellers who want to pair coast time with a wider Kenyan nature experience. Ask about current route options.",
    highlights: ["Tsavo", "Wildlife planning", "Coast and inland"],
    featured: false,
  },
];

const stayEntries = [
  {
    id: "whitebeach-residence",
    slug: "whitebeach-residence",
    name: "Whitebeach Residence",
    category: "Residence",
    location: "Location to confirm",
    image: photos.beach,
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
    relationship: "Managed by Visit Malindi",
    description: "A Visit Malindi-managed property profile. Ask us to confirm the current property details, dates and best fit for your stay.",
    amenities: [],
    suitableFor: [],
    suitableForNote: "Confirm the best fit for your group with Visit Malindi.",
    tags: ["Residences", "Managed accommodation"],
    usefulInfo: ["Current property details, rates and availability are confirmed through WhatsApp.", "Website and social links will be added when approved details are supplied.", "This website does not process online bookings or payments."],
  },
  {
    id: "via-lattea-residence",
    slug: "via-lattea-residence",
    name: "Via Lattea Residence",
    category: "Residence",
    location: "Location to confirm",
    image: photos.sunset,
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
    relationship: "Managed by Visit Malindi",
    description: "A Visit Malindi-managed property profile. Ask us to confirm the current property details, dates and best fit for your stay.",
    amenities: [],
    suitableFor: [],
    suitableForNote: "Confirm the best fit for your group with Visit Malindi.",
    tags: ["Residences", "Managed accommodation"],
    usefulInfo: ["Current property details, rates and availability are confirmed through WhatsApp.", "Website and social links will be added when approved details are supplied.", "This website does not process online bookings or payments."],
  },
  {
    id: "casuarina-villas",
    slug: "villas-in-casuarina-malindi",
    name: "Villas in Casuarina, Malindi",
    category: "Villas",
    location: "Casuarina, Malindi",
    image: photos.beach,
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
    relationship: "Visit Malindi Partner",
    description: "A partner accommodation guide for visitors looking for villa options in Casuarina, Malindi. Ask Visit Malindi for current property choices and details.",
    amenities: [],
    suitableFor: [],
    suitableForNote: "Tell us about your group and we will help you ask the right questions.",
    tags: ["Villas", "Partner accommodation"],
  },
  {
    id: "hotels-in-malindi",
    slug: "hotels-in-malindi",
    name: "Hotels in Malindi",
    category: "Hotel",
    location: "Malindi",
    image: photos.hero,
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
    relationship: "Visit Malindi Partner",
    description: "A partner accommodation guide for hotels in Malindi. Share your dates, group and preferred feel so Visit Malindi can point you in the right direction.",
    amenities: [],
    suitableFor: [],
    suitableForNote: "Options can be matched to your group and plans after a direct enquiry.",
    tags: ["Hotels", "Partner accommodation"],
  },
  {
    id: "boutique-hotels",
    slug: "boutique-hotels",
    name: "Boutique hotels",
    category: "Boutique Hotel",
    location: "Location to confirm",
    image: photos.sunset,
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
    relationship: "Visit Malindi Partner",
    description: "A partner accommodation guide for boutique hotel options. Ask Visit Malindi about current properties, locations and availability.",
    amenities: [],
    suitableFor: [],
    suitableForNote: "Confirm location and the best match for your stay through WhatsApp.",
    tags: ["Hotels", "Boutique Stays", "Partner accommodation"],
  },
  {
    id: "luxury-properties",
    slug: "luxury-properties",
    name: "Luxury properties",
    category: "Luxury Property",
    location: "Location to confirm",
    image: photos.ocean,
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
    relationship: "Visit Malindi Partner",
    description: "A partner accommodation guide for luxury property options on the coast. Ask Visit Malindi to confirm current choices and details.",
    amenities: [],
    suitableFor: [],
    suitableForNote: "Tell us what matters to you before we suggest a direction.",
    tags: ["Luxury Stays", "Partner accommodation"],
  },
  {
    id: "watamu-accommodation",
    slug: "accommodation-in-watamu",
    name: "Accommodation in Watamu",
    category: "Accommodation Facility",
    location: "Watamu",
    image: photos.mangrove,
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
    relationship: "Visit Malindi Partner",
    description: "A partner accommodation guide for facilities in Watamu. Ask Visit Malindi for current options based on your dates and plans.",
    amenities: [],
    suitableFor: [],
    suitableForNote: "Confirm the property, location and best fit for your group through WhatsApp.",
    tags: ["Hotels", "Guesthouses", "Partner accommodation"],
  },
  {
    id: "beachfront-stays",
    slug: "beachfront-stays",
    name: "Beachfront stays in Malindi",
    category: "Beach Resort",
    location: "Malindi",
    image: photos.beach,
    description: "Wake up close to the Indian Ocean. Tell us your dates, group and preferred feel, and we will help you explore suitable beachfront options.",
    amenities: ["Beach access", "Relaxed coastal setting", "Options for couples and families"],
    tags: ["Hotels", "Resorts", "Beachfront Stays", "Luxury Stays"],
    relationship: "General accommodation",
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
  },
  {
    id: "boutique-stays",
    slug: "boutique-stays",
    name: "Boutique stays",
    category: "Boutique Hotel",
    location: "Malindi",
    image: photos.sunset,
    description: "Smaller, characterful places to stay for travellers who want a more personal base in Malindi.",
    amenities: ["Local character", "Personalised recommendations", "Central coastal location"],
    tags: ["Hotels", "Boutique Stays"],
    relationship: "General accommodation",
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
  },
  {
    id: "family-stays",
    slug: "family-stays",
    name: "Family-friendly stays",
    category: "Family Stay",
    location: "Malindi & Watamu",
    image: photos.family,
    description: "A starting point for finding the right space for a family holiday, from easy beach days to a base for exploring.",
    amenities: ["Family-friendly options", "Flexible locations", "Local trip support"],
    tags: ["Hotels", "Apartments", "Guesthouses", "Budget Stays"],
    relationship: "General accommodation",
    imageIsIllustrative: true,
    imageCaption: "Illustrative coastal image — confirm current property details with Visit Malindi.",
  },
];

const foodEntries = [
  {
    id: "lion-in-the-sun",
    slug: "lion-in-the-sun-restaurant",
    name: "Lion in the Sun Restaurant",
    category: "Fine Dining",
    location: "Malindi",
    image: photos.dining,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "A named fine-dining restaurant in Malindi. Visit Malindi can take a reservation enquiry and confirm the current dining details.",
    tags: ["Restaurants"],
    sourceUrl: "https://www.malindirestaurants.com/restaurant/lion-in-the-sun-fine-dining-restaurant-malindi-kenya/profile",
  },
  {
    id: "victoria-restaurant",
    slug: "victoria-restaurant",
    name: "Victoria Restaurant",
    category: "Restaurant",
    location: "Malindi",
    image: photos.dining,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "A named Malindi restaurant at Ocean Beach Resort & Spa. Ask Visit Malindi to make a table enquiry around your plans.",
    tags: ["Fine Dining", "Restaurants"],
    websiteUrl: "https://www.oceanbeachkenya.com/restaurants-and-bars-in-malindi/victoria-restaurant-in-malindi/",
  },
  {
    id: "billionaire-grill-bar",
    slug: "billionaire-grill-and-bar",
    name: "Billionaire Grill & Bar",
    category: "Beach Restaurant",
    location: "Malindi",
    image: photos.sunset,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "A named beach restaurant and bar in Malindi. Ask Visit Malindi about a table, an evening plan or current venue information.",
    tags: ["Restaurants", "Bars", "Lounges"],
    sourceUrl: "https://www.malindirestaurants.com/restaurant/billionaire-grill-bar-beach-restaurant-malindi-kenya/profile",
  },
  {
    id: "retro-and-co",
    slug: "retro-and-co-coffee-bar",
    name: "Retro & Co Coffee Bar",
    category: "Café",
    location: "Malindi",
    image: photos.dining,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "An independent bookstore and coffee bar in Malindi for visitors looking for a coffee-and-reading stop.",
    tags: ["Cafés", "Casual Dining"],
    websiteUrl: "https://retroandcobookstore.com/pages/about-us",
  },
  {
    id: "lorenzos-restaurant",
    slug: "lorenzos-restaurant",
    name: "Lorenzos Restaurant",
    category: "Restaurant",
    location: "Malindi",
    image: photos.dining,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "A named restaurant at Mwembe Resort in Malindi, with Italian, continental and African dishes described by the venue.",
    tags: ["Restaurants", "Local food"],
    websiteUrl: "https://mwemberesort.com/restaurant/",
  },
  {
    id: "mannis-restaurant",
    slug: "mannis-fine-dining-and-cocktail-bar",
    name: "Mannis Fine Dining & Cocktail Bar",
    category: "Fine Dining",
    location: "Watamu",
    image: photos.sunset,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "A named fine-dining restaurant and premium cocktail bar in Watamu, with coastal-inspired Italian dining described by the venue.",
    tags: ["Restaurants", "Seafood", "Bars", "Lounges"],
    websiteUrl: "https://www.palmgardenkenya.com/mannisrestaurant",
  },
  {
    id: "gk-restaurant-bar",
    slug: "gk-restaurant-and-bar",
    name: "GK Restaurant & Bar",
    category: "Restaurant",
    location: "Watamu",
    image: photos.dining,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "A named Watamu restaurant and bar. The venue describes local and international dishes, fresh fish and sunset cocktails.",
    tags: ["Restaurants", "Seafood", "Local food", "Bars"],
    websiteUrl: "https://gkpalmsresort.com/gk-restaurant/",
  },
  {
    id: "kobe-beach-restaurant",
    slug: "kobe-beach-restaurant-and-cocktail-bar",
    name: "Kobe Beach Restaurant & Cocktail Bar",
    category: "Beach Restaurant",
    location: "Watamu",
    image: photos.beach,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "A named beach restaurant and cocktail bar in Watamu, with seaside dining, fresh fish and sunset cocktails described by the venue.",
    tags: ["Restaurants", "Seafood", "Bars", "Lounges"],
    websiteUrl: "https://www.kobesuiteresort.com/restaurants/",
  },
  {
    id: "star-lounge",
    slug: "star-lounge-watamu",
    name: "Star Lounge",
    category: "Lounge",
    location: "Watamu",
    image: photos.sunset,
    imageIsIllustrative: true,
    imageCaption: "Illustrative dining image — confirm current venue details with Visit Malindi.",
    description: "A named rooftop lounge in Watamu for cocktails and tapas. Ask Visit Malindi to confirm the current details for your evening.",
    tags: ["Bars", "Lounges"],
    websiteUrl: "https://www.medinapalms.com/dining/star-lounge/",
  },
];

const nightlifeEntries = [
  {
    id: "billionaire-grill-bar-night",
    slug: "billionaire-grill-and-bar-malindi",
    name: "Billionaire Grill & Bar",
    category: "Beach Bar",
    location: "Malindi",
    image: photos.night,
    imageIsIllustrative: true,
    imageCaption: "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
    listingKind: "Permanent venue",
    description: "A named Malindi beach bar and restaurant for a dinner-to-drinks plan. Ask Visit Malindi about current arrangements.",
    tags: ["Bars", "Lounges", "Beach Nightlife"],
    sourceUrl: "https://www.malindirestaurants.com/restaurant/billionaire-grill-bar-beach-restaurant-malindi-kenya/profile",
  },
  {
    id: "rosada-beach",
    slug: "rosada-beach-malindi",
    name: "Rosada Beach",
    category: "Beach Bar",
    location: "Malindi",
    image: photos.beach,
    imageIsIllustrative: true,
    imageCaption: "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
    listingKind: "Permanent venue",
    description: "A named Malindi beach venue associated with food, drinks and beach-led evenings. Ask the concierge what is currently on.",
    tags: ["Bars", "Beach Nightlife"],
    sourceUrl: "https://www.malindikenya.net/en/articles/tourism/events/music-in-october-in-malindi-with-rosada-evenings.html",
  },
  {
    id: "stardust-malindi",
    slug: "stardust-malindi",
    name: "Stardust Malindi",
    category: "Club",
    location: "Malindi",
    image: photos.night,
    imageIsIllustrative: true,
    imageCaption: "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
    listingKind: "Permanent venue",
    description: "A named Malindi club venue. Ask Visit Malindi for current entry, music and transport information before making plans.",
    tags: ["Clubs"],
    sourceUrl: "https://malindians.com/entertainment/celebrity-saturday-at-stardust-malindi/",
  },
  {
    id: "star-lounge-night",
    slug: "star-lounge-watamu",
    name: "Star Lounge",
    category: "Lounge",
    location: "Watamu",
    image: photos.sunset,
    imageIsIllustrative: true,
    imageCaption: "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
    listingKind: "Permanent venue",
    description: "A named Watamu rooftop lounge for an early-evening drinks plan. Ask Visit Malindi to confirm current venue information.",
    tags: ["Bars", "Lounges"],
    websiteUrl: "https://www.medinapalms.com/dining/star-lounge/",
  },
  {
    id: "mannis-cocktail-bar-night",
    slug: "mannis-cocktail-bar-watamu",
    name: "Mannis Premium Cocktail Bar",
    category: "Cocktail Bar",
    location: "Watamu",
    image: photos.night,
    imageIsIllustrative: true,
    imageCaption: "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
    listingKind: "Permanent venue",
    description: "A named Watamu cocktail bar paired with Mannis Fine Dining. Ask Visit Malindi to coordinate dinner and drinks.",
    tags: ["Bars", "Lounges"],
    websiteUrl: "https://www.palmgardenkenya.com/mannisrestaurant",
  },
  {
    id: "kobe-cocktail-bar-night",
    slug: "kobe-cocktail-bar-watamu",
    name: "Kobe Cocktail Bar",
    category: "Beach Bar",
    location: "Watamu",
    image: photos.beach,
    imageIsIllustrative: true,
    imageCaption: "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
    listingKind: "Permanent venue",
    description: "A named Watamu beach cocktail bar for sunset drinks and a beach-led evening. Confirm the current details through Visit Malindi.",
    tags: ["Bars", "Lounges", "Beach Nightlife"],
    websiteUrl: "https://www.kobesuiteresort.com/restaurants/",
  },
  {
    id: "lichthaus-watamu",
    slug: "lichthaus-watamu",
    name: "Lichthaus",
    category: "Creek Bar",
    location: "Watamu",
    image: photos.sunset,
    imageIsIllustrative: true,
    imageCaption: "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
    listingKind: "Permanent venue",
    description: "A named Watamu venue by Mida Creek for a slower drinks plan. Ask Visit Malindi for current access, transport and local guidance.",
    tags: ["Bars", "Lounges"],
  },
  {
    id: "paparemo-beach",
    slug: "paparemo-beach-watamu",
    name: "Paparemo Beach",
    category: "Beach Venue",
    location: "Watamu",
    image: photos.night,
    imageIsIllustrative: true,
    imageCaption: "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
    listingKind: "Permanent venue",
    description: "A named Watamu beach venue for social evenings. Ask the concierge what is currently happening before you go.",
    tags: ["Beach Nightlife", "Bars"],
    sourceUrl: "https://www.malindikenya.net/en/articles/tourism/events/watamu-is-back-with-paparemo-s-iconic-beach-party.html",
  },
];

const transferEntries = [
  { id: "malindi-airport-malindi", slug: "malindi-airport-to-malindi", route: "Malindi Airport ↔ Malindi", category: "Airport Transfers", location: "Malindi", image: photos.dhow, description: "Request a connection between Malindi Airport and your Malindi accommodation or plans.", typicalUse: "For arrivals, departures or an airport leg that needs to fit around your accommodation, luggage and wider plans." },
  { id: "malindi-airport-watamu", slug: "malindi-airport-to-watamu", route: "Malindi Airport ↔ Watamu", category: "Airport Transfers", location: "Malindi & Watamu", image: photos.ocean, description: "Request an airport connection between Malindi Airport and Watamu.", typicalUse: "For visitors using Malindi Airport while staying in, or continuing to, Watamu." },
  { id: "mombasa-airport-malindi", slug: "mombasa-airport-to-malindi", route: "Mombasa Airport ↔ Malindi", category: "Airport Transfers", location: "Mombasa & Malindi", image: photos.dhow, description: "Request a coast connection between Mombasa Airport and Malindi.", typicalUse: "For international or domestic arrivals and departures that need a road transfer to or from Malindi." },
  { id: "mombasa-airport-watamu", slug: "mombasa-airport-to-watamu", route: "Mombasa Airport ↔ Watamu", category: "Airport Transfers", location: "Mombasa & Watamu", image: photos.ocean, description: "Request a coast connection between Mombasa Airport and Watamu.", typicalUse: "For arrivals and departures that need to connect Mombasa Airport with a Watamu stay or itinerary." },
  { id: "mombasa-sgr-malindi", slug: "sgr-to-malindi", route: "Mombasa SGR ↔ Malindi", category: "SGR Transfers", location: "Mombasa & Malindi", image: photos.beach, description: "Request the road connection between Mombasa SGR and Malindi.", typicalUse: "For travellers arriving at, or departing from, Mombasa SGR and continuing their trip to Malindi." },
  { id: "mombasa-sgr-watamu", slug: "mombasa-sgr-to-watamu", route: "Mombasa SGR ↔ Watamu", category: "SGR Transfers", location: "Mombasa & Watamu", image: photos.beach, description: "Request the road connection between Mombasa SGR and Watamu.", typicalUse: "For travellers arriving at, or departing from, Mombasa SGR and continuing their trip to Watamu." },
  { id: "malindi-watamu", slug: "malindi-to-watamu", route: "Malindi ↔ Watamu", category: "Intercity", location: "Malindi & Watamu", image: photos.ocean, description: "Request an intercity transfer between Malindi and Watamu.", typicalUse: "For moving between the two destinations while keeping your beach, dining, activity or accommodation plans connected." },
  { id: "malindi-kilifi", slug: "malindi-to-kilifi", route: "Malindi ↔ Kilifi", category: "Intercity", location: "Malindi & Kilifi", image: photos.ocean, description: "Request an intercity transfer between Malindi and Kilifi.", typicalUse: "For a coast leg between Malindi and Kilifi, whether it is part of a stay, a day out or a wider itinerary." },
  { id: "malindi-mombasa", slug: "malindi-to-mombasa", route: "Malindi ↔ Mombasa", category: "Intercity", location: "Malindi & Mombasa", image: photos.dhow, description: "Request an intercity transfer between Malindi and Mombasa.", typicalUse: "For travellers linking Malindi with Mombasa without needing to present fixed routes, vehicles or schedules on the site." },
  { id: "malindi-mambrui", slug: "malindi-to-mambrui", route: "Malindi ↔ Mambrui", category: "Intercity", location: "Malindi & Mambrui", image: photos.beach, description: "Request an intercity transfer between Malindi and Mambrui.", typicalUse: "For a north-coast connection that can be shaped around the rest of your plans." },
  { id: "malindi-lamu", slug: "malindi-to-lamu", route: "Malindi ↔ Lamu", category: "Intercity", location: "Malindi & Lamu", image: photos.dhow, description: "Ask Visit Malindi for help planning a Malindi and Lamu connection.", typicalUse: "For wider coast travel where the most suitable current arrangements need to be confirmed manually." },
  { id: "hotel-restaurant", slug: "hotel-to-restaurant", route: "Hotel → Restaurant", category: "Local & Experience Transfers", location: "Malindi & Watamu", image: photos.dining, description: "Request local transport between your accommodation and a restaurant plan.", typicalUse: "For dinner plans that need a simple connection from your stay, especially when you would rather not work out the local logistics alone." },
  { id: "hotel-excursion", slug: "hotel-to-excursion", route: "Hotel → Excursion", category: "Local & Experience Transfers", location: "Malindi & Watamu", image: photos.ocean, description: "Request local transport between your accommodation and an excursion or activity.", typicalUse: "For fitting a chosen activity or day trip into the practical start and end of your day." },
  { id: "hotel-nightlife", slug: "hotel-to-nightlife", route: "Hotel → Nightlife", category: "Local & Experience Transfers", location: "Malindi & Watamu", image: photos.night, description: "Request transport between your accommodation and an evening or nightlife plan.", typicalUse: "For dinner, drinks, group evenings and a safer-feeling route back to your accommodation." },
  { id: "hotel-airport-sgr", slug: "hotel-to-airport-or-sgr", route: "Hotel → Airport / SGR", category: "Local & Experience Transfers", location: "Malindi & Watamu", image: photos.dhow, description: "Request a connection between your accommodation and an airport or SGR departure.", typicalUse: "For departure-day planning when your stay and onward connection need to be coordinated." },
  { id: "private-day-trip", slug: "private-day-trip-transport", route: "Private day-trip transport", category: "Local & Experience Transfers", location: "Malindi & Watamu", image: photos.mangrove, description: "Request transport for a privately planned coast day.", typicalUse: "For a flexible day shaped around the places, stops and pace that matter to you." },
  { id: "group-transport", slug: "group-transport", route: "Group transport", category: "Local & Experience Transfers", location: "Malindi & Watamu", image: photos.family, description: "Request transport planning for a group.", typicalUse: "For friends, families and other groups who want to coordinate a shared arrival, day out, dinner or evening." },
];

const attractionEntries = [
  { id: "malindi-marine-park-place", slug: "malindi-marine-national-park", name: "Malindi Marine National Park", category: "Nature", location: "Malindi", image: photos.ocean, description: "A marine destination to consider when planning time on the water in Malindi. Ask Visit Malindi about current ways to experience it." },
  { id: "malindi-beaches", slug: "malindi-beaches", name: "Malindi beaches", category: "Beach", location: "Malindi", image: photos.beach, description: "Find your kind of beach day, from a quiet shoreline to the easy rhythm of a family afternoon." },
  { id: "vasco-da-gama-pillar", slug: "vasco-da-gama-pillar", name: "Vasco da Gama Pillar", category: "Historical", location: "Malindi", image: photos.ocean, description: "A landmark on the Malindi waterfront and a natural stop while exploring the old town and coast." },
  { id: "malindi-museum", slug: "malindi-museum", name: "Malindi Museum", category: "Historical", location: "Malindi", image: photos.ruins, description: "A place to add context to Malindi's coastal history and culture. Ask about current visiting information before you go." },
  { id: "portuguese-chapel", slug: "portuguese-chapel", name: "Portuguese Chapel", category: "Historical", location: "Malindi", image: photos.ruins, description: "A historic place to include in a slower exploration of Malindi's old town and waterfront." },
  { id: "silversands", slug: "silversands", name: "Silversands", category: "Beach", location: "Malindi", image: photos.beach, description: "A quieter coastal setting for travellers looking to build a beach-led day around Malindi." },
  { id: "casuarina", slug: "casuarina", name: "Casuarina", category: "Beach", location: "Malindi", image: photos.beach, description: "Explore the Casuarina side of Malindi at your own pace, with local guidance on what to do nearby." },
  { id: "watamu-marine-park-place", slug: "watamu-marine-national-park", name: "Watamu Marine National Park", category: "Nature", location: "Watamu", image: photos.ocean, description: "A marine destination on the Watamu coast, with current visit and experience information available through the concierge." },
  { id: "watamu-beaches", slug: "watamu-beaches", name: "Watamu beaches", category: "Beach", location: "Watamu", image: photos.beach, description: "A starting point for finding your kind of Watamu beach day, from easy swimming time to a base for exploring." },
  { id: "mida-creek-place", slug: "mida-creek", name: "Mida Creek", category: "Nature", location: "Watamu", image: photos.midaCreek, description: "A Watamu-side coastal creek known for its mangrove setting and wide tidal views. Confirm current visit options before you go." },
  { id: "gede-ruins-place", slug: "gede-ruins", name: "Gede Ruins", category: "Historical", location: "Gede", image: photos.ruins, description: "Historic Swahili settlement remains set near the coastal forest. Ask Visit Malindi for current visit details when planning your day." },
  { id: "arabuko-sokoke", slug: "arabuko-sokoke-forest", name: "Arabuko Sokoke Forest", category: "Nature", location: "Wider Coast", image: photos.mangrove, description: "A nature-led change of pace for travellers who want to add forest, walks or birding to their coast plans." },
  { id: "sabaki-river", slug: "sabaki-river", name: "Sabaki River", category: "Nature", location: "Wider Coast", image: photos.mangrove, description: "A wider-coast destination to consider when shaping a trip beyond the beach." },
  { id: "mambrui", slug: "mambrui", name: "Mambrui", category: "Culture", location: "Mambrui", image: photos.beach, description: "Add Mambrui to a wider Kenyan Coast route when you want to explore beyond Malindi's centre." },
  { id: "kilifi", slug: "kilifi", name: "Kilifi", category: "Culture", location: "Kilifi", image: photos.ocean, description: "A wider-coast stop to consider alongside Malindi and Watamu, depending on the shape of your trip." },
  { id: "marafa-hells-kitchen", slug: "marafa-hells-kitchen", name: "Marafa / Hell's Kitchen", category: "Nature", location: "Marafa", image: photos.ruins, description: "A distinctive inland landscape to consider as part of a wider coast itinerary. Confirm current travel details before arranging the day." },
  { id: "mombasa-place", slug: "mombasa-day-visit", name: "Mombasa day visit", category: "Culture", location: "Mombasa", image: photos.dhow, description: "A wider-coast destination to consider when building a longer Kenyan Coast itinerary." },
  { id: "tsavo-experiences", slug: "tsavo-experiences", name: "Tsavo experiences", category: "Nature", location: "Wider Kenyan Coast", image: photos.mangrove, description: "For visitors looking to pair coast time with a wider Kenyan nature experience, ask Visit Malindi about current ways to shape the route." },
  { id: "malindi-old-town", slug: "malindi-old-town", name: "Malindi Old Town", category: "Culture", location: "Malindi", image: photos.ruins, description: "Take a slower walk through the layers of coastal history, culture and everyday life." },
];

const itineraryEntries = [
  { id: "1-day-malindi", slug: "1-day-in-malindi", name: "1 Day in Malindi", duration: "1 day", audience: "First-time visitors", image: photos.beach, description: "A taste of sea, history and a sunset when you only have a day.", days: [{ day: 1, activities: ["Morning by the ocean", "A local lunch", "Sunset by the coast"] }] },
  { id: "2-days-malindi", slug: "2-days-in-malindi", name: "2 Days in Malindi", duration: "2 days", audience: "First-time visitors", image: photos.dhow, description: "Two unhurried days for getting your bearings, feeling the coast and finding a little more of Malindi.", days: [{ day: 1, activities: ["Settle in", "Explore the coast", "An easy evening"] }, { day: 2, activities: ["Choose an experience", "A local lunch", "Sunset plans"] }] },
  { id: "3-days-malindi", slug: "3-days-in-malindi", name: "3 Days in Malindi", duration: "3 days", audience: "General", image: photos.ocean, description: "A balanced first trip with room for marine time, culture, good food and slow mornings.", days: [{ day: 1, activities: ["Settle into the coast", "Explore Malindi", "Sunset plans"] }, { day: 2, activities: ["Marine or beach experience", "Lunch by the water", "A night out"] }, { day: 3, activities: ["Gede Ruins or nature", "Local flavours", "One last ocean view"] }] },
  { id: "weekend-malindi", slug: "weekend-in-malindi", name: "Weekend in Malindi", duration: "Weekend", audience: "Couples & friends", image: photos.sunset, description: "A compact coast reset: arrive, exhale, explore and leave with salt in your hair.", days: [{ day: 1, activities: ["Arrival and beach time", "Dinner", "Ask what is happening tonight"] }, { day: 2, activities: ["Choose a marine or nature experience", "A slow afternoon", "Sunset"] }] },
  { id: "malindi-watamu", slug: "malindi-and-watamu", name: "Malindi + Watamu", duration: "Flexible", audience: "Explorers", image: photos.mangrove, description: "See two sides of the coast, with time for Malindi's character and Watamu's nature-led pace.", days: [{ day: 1, activities: ["Malindi highlights", "Coastal dining"] }, { day: 2, activities: ["Watamu or Mida Creek", "Sunset by the water"] }] },
  { id: "malindi-tsavo", slug: "malindi-and-tsavo", name: "Malindi + Tsavo", duration: "Flexible", audience: "Adventure seekers", image: photos.mangrove, description: "A coast-and-nature starting point for travellers who want to add a wider Kenyan adventure to their beach time.", days: [{ day: 1, activities: ["Coastal arrival", "Plan your next move"] }, { day: 2, activities: ["Ask for current travel options", "Shape the trip around your interests"] }] },
  { id: "family-holiday", slug: "family-holiday", name: "Family Holiday", duration: "Flexible", audience: "Families", image: photos.family, description: "An easy-going framework for a family trip with flexible beach, nature and food ideas.", days: [{ day: 1, activities: ["Easy beach morning", "Family-friendly lunch"] }, { day: 2, activities: ["Nature or marine discovery", "Slow evening"] }] },
  { id: "honeymoon", slug: "honeymoon", name: "Honeymoon by the Coast", duration: "Flexible", audience: "Couples", image: photos.dhow, description: "A romantic starting point for a trip shaped around unhurried days and beautiful evenings.", days: [{ day: 1, activities: ["Oceanfront arrival", "Sunset together"] }, { day: 2, activities: ["Private experience enquiry", "Romantic dining"] }] },
  { id: "couples-getaway", slug: "couples-getaway", name: "Couple's Getaway", duration: "Flexible", audience: "Couples", image: photos.sunset, description: "A simple coast escape for two, shaped around your preferred balance of beach time, food and adventure.", days: [{ day: 1, activities: ["Slow arrival", "A memorable dinner"] }, { day: 2, activities: ["Choose your pace", "One more sunset"] }] },
  { id: "adventure-trip", slug: "adventure-trip", name: "Adventure Trip", duration: "Flexible", audience: "Active travellers", image: photos.ocean, description: "Build a coastal itinerary around time on the water, outdoor experiences and the kind of days you remember.", days: [{ day: 1, activities: ["Choose your adventure", "Rest by the coast"] }, { day: 2, activities: ["More outdoors", "Share your highlights over dinner"] }] },
  { id: "relaxation-trip", slug: "relaxation-trip", name: "Relaxation Trip", duration: "Flexible", audience: "Slow travellers", image: photos.beach, description: "For travellers who would rather leave the schedule open and let the coast set the pace.", days: [{ day: 1, activities: ["Arrive and exhale", "A quiet meal"] }, { day: 2, activities: ["Beach time", "Sunset"] }] },
];

const experienceTypesByCategory = {
  "Marine": ["Marine"],
  "Snorkelling": ["Marine"],
  "Diving": ["Marine", "Adventure"],
  "Dolphin Experiences": ["Marine", "Nature"],
  "Sunset Cruises": ["Marine", "Couples", "Relaxation"],
  "Sandbank": ["Marine", "Family", "Couples"],
  "Water Sports": ["Marine", "Adventure"],
  "Beach Activities": ["Family", "Relaxation"],
  "Boat Trips": ["Marine", "Adventure"],
  "Fishing": ["Marine", "Adventure"],
  "Nature": ["Nature"],
  "Wildlife": ["Nature"],
  "History & Culture": ["Culture"],
  "Adventure": ["Adventure"],
  "Family Activities": ["Family"],
  "Couples & Romantic": ["Couples", "Relaxation"],
  "Photography": ["Photography"],
  "Wellness": ["Relaxation"],
  "Day Trip": ["Day Trip"],
  "Culture": ["Culture", "Day Trip"],
  "Culture & Nature": ["Culture", "Nature", "Day Trip"],
};

const experienceProfiles = {
  "malindi-marine-national-park": { fullDescription: "Malindi Marine National Park is a useful starting point for a water-led day on the coast. Visit Malindi can help match your group with an appropriate current way to spend time on the water, while keeping conditions and responsible practice front of mind.", suitableFor: ["First-time visitors", "Families", "Marine enthusiasts"], nearbyPlaces: [{ label: "Malindi beaches", path: "/attraction/malindi-beaches" }, { label: "Vasco da Gama Pillar", path: "/attraction/vasco-da-gama-pillar" }] },
  "watamu-marine-national-park": { fullDescription: "Watamu Marine National Park is part of a coast day that can be as active or as relaxed as you want it to be. Use the concierge to confirm current options, practical details and a route that works with the rest of your time in Watamu.", suitableFor: ["Couples", "Families", "Marine enthusiasts"], nearbyPlaces: [{ label: "Watamu beaches", path: "/attraction/watamu-beaches" }, { label: "Mida Creek", path: "/attraction/mida-creek" }] },
  "mida-creek-sunset": { fullDescription: "Mida Creek offers a slower contrast to an ocean-facing day, with mangrove waterways and wide tidal horizons near Watamu. The right way to experience it can depend on conditions, timing and what you want to pair it with.", suitableFor: ["Couples", "Nature lovers", "Photographers"], nearbyPlaces: [{ label: "Watamu beaches", path: "/attraction/watamu-beaches" }, { label: "Gede Ruins", path: "/attraction/gede-ruins" }] },
  "gede-ruins": { fullDescription: "Gede Ruins brings historic Swahili settlement remains and a coastal-forest setting into the same visit. It works well for travellers who want their beach trip to include history, culture and a change of pace.", suitableFor: ["History lovers", "Families", "Curious explorers"], nearbyPlaces: [{ label: "Arabuko Sokoke Forest", path: "/attraction/arabuko-sokoke-forest" }, { label: "Mida Creek", path: "/attraction/mida-creek" }] },
  "dhow-sailing": { fullDescription: "Dhow sailing is an unhurried way to see the coastline from the water. The concierge can help you ask about the current options, timing and whether a daytime or sunset-led route suits your group.", suitableFor: ["Couples", "Friends", "First-time visitors"], nearbyPlaces: [{ label: "Malindi beaches", path: "/attraction/malindi-beaches" }, { label: "Watamu beaches", path: "/attraction/watamu-beaches" }] },
  "glass-bottom-boat": { fullDescription: "A glass-bottom boat experience is a gentle option for travellers who want a water-based coast day without needing to build the whole plan around an active experience. Ask Visit Malindi about current routes and the best fit for your group.", suitableFor: ["Families", "First-time visitors", "Mixed-age groups"], nearbyPlaces: [{ label: "Malindi Marine National Park", path: "/attraction/malindi-marine-national-park" }, { label: "Watamu Marine National Park", path: "/attraction/watamu-marine-national-park" }] },
  "gede-arabuko-excursion": { fullDescription: "This wider-coast excursion combines Gede's heritage setting with the surrounding coastal forest region. It is a strong choice when you want to step beyond the beach and add both history and nature to one day.", suitableFor: ["Nature lovers", "History lovers", "Photographers"], nearbyPlaces: [{ label: "Gede Ruins", path: "/attraction/gede-ruins" }, { label: "Arabuko Sokoke Forest", path: "/attraction/arabuko-sokoke-forest" }] },
  "marafa-excursion": { fullDescription: "Marafa / Hell's Kitchen offers a distinct inland landscape as part of a wider Coast itinerary. Travel planning, route conditions and the right timing should be confirmed with the concierge before arranging the day.", suitableFor: ["Adventure seekers", "Photographers", "Wider-coast explorers"], nearbyPlaces: [{ label: "Marafa / Hell's Kitchen", path: "/attraction/marafa-hells-kitchen" }, { label: "Mambrui", path: "/attraction/mambrui" }] },
};

const popularExperienceIds = new Set(["malindi-marine-national-park", "watamu-marine-national-park", "mida-creek-sunset", "gede-ruins", "dhow-sailing", "glass-bottom-boat", "watamu-mida-creek-excursion", "gede-arabuko-excursion"]);

function defaultNearbyPlaces(location = "") {
  if (location.includes("Watamu") || location.includes("Mida")) return [{ label: "Watamu beaches", path: "/attraction/watamu-beaches" }, { label: "Mida Creek", path: "/attraction/mida-creek" }];
  if (location.includes("Gede")) return [{ label: "Gede Ruins", path: "/attraction/gede-ruins" }, { label: "Arabuko Sokoke Forest", path: "/attraction/arabuko-sokoke-forest" }];
  if (location.includes("Malindi")) return [{ label: "Malindi beaches", path: "/attraction/malindi-beaches" }, { label: "Malindi Old Town", path: "/attraction/malindi-old-town" }];
  return [{ label: "Places to visit", path: "/places-to-visit" }, { label: "Excursions from Malindi", path: "/excursions" }];
}

function destinationPlanningLink(location = "") {
  if (location.includes("Malindi")) return { label: "Discover Malindi", path: "/malindi" };
  if (location.includes("Watamu") || location.includes("Mida") || location.includes("Gede")) return { label: "Discover Watamu", path: "/watamu" };
  return null;
}

function enrichDiscoveryItem(item) {
  const profile = experienceProfiles[item.id] || {};
  const experienceTypes = item.experienceTypes || experienceTypesByCategory[item.category] || ["Day Trip"];
  const destinationLink = destinationPlanningLink(item.location);
  return {
    ...item,
    experienceTypes: [...new Set([...experienceTypes, ...(item.tags || []).filter((tag) => ["Adventure", "Family", "Couples", "Nature", "Culture", "Marine", "Food", "Relaxation", "Photography", "Day Trip"].includes(tag))])],
    popular: popularExperienceIds.has(item.id),
    fullDescription: profile.fullDescription || `${item.description} This is a concierge-led experience guide rather than an operator listing, so Visit Malindi can help you confirm current practical details before you make arrangements.`,
    suitableFor: profile.suitableFor || (experienceTypes.includes("Family") ? ["Families", "Friends", "First-time visitors"] : experienceTypes.includes("Couples") ? ["Couples", "Slow travellers", "First-time visitors"] : ["Curious travellers", "Friends", "Independent explorers"]),
    whatToExpect: item.whatToExpect || ["A day shaped around your interests and the current conditions", "Practical details confirmed with the Visit Malindi concierge", "A flexible starting point rather than a fixed commercial package"],
    nearbyPlaces: profile.nearbyPlaces || defaultNearbyPlaces(item.location),
    planningLinks: [
      destinationLink,
      { label: "Places to visit", path: "/places-to-visit" },
      { label: "Places to stay", path: "/places-to-stay" },
      { label: "Eat & drink", path: "/eat-and-drink" },
      { label: "Nightlife", path: "/nightlife" },
      { label: "Transfers", path: "/transfers" },
      { label: "Itineraries", path: "/itineraries" },
      { label: "What's on", path: "/whats-on" },
    ].filter(Boolean),
  };
}

const withListingFields = (item) => ({
  ...item,
  images: item.images || item.gallery || (item.image ? [item.image] : []),
  gallery: item.gallery || item.images || (item.image ? [item.image] : []),
  usefulInfo: item.usefulInfo || ["Ask Visit Malindi about current availability, pricing and the best fit for your plans."],
  mapUrl: item.mapUrl || null,
  websiteUrl: item.websiteUrl || null,
  socialUrl: item.socialUrl || null,
  sourceUrl: item.sourceUrl || null,
});

const stayPlanningLinks = [
  { label: "Places to visit", path: "/places-to-visit" },
  { label: "Things to do", path: "/things-to-do" },
  { label: "Excursions", path: "/excursions" },
  { label: "Eat & drink", path: "/eat-and-drink" },
  { label: "Need airport or SGR transfer? Arrange with Visit Malindi.", path: "/transfers" },
  { label: "Itineraries", path: "/itineraries" },
];

function stayNearbyPlaces(location = "") {
  if (location.includes("Watamu")) return [{ label: "Watamu beaches", path: "/attraction/watamu-beaches" }, { label: "Mida Creek", path: "/attraction/mida-creek" }];
  if (location.includes("Casuarina")) return [{ label: "Casuarina", path: "/attraction/casuarina" }, { label: "Malindi beaches", path: "/attraction/malindi-beaches" }];
  if (location.includes("Malindi")) return [{ label: "Malindi beaches", path: "/attraction/malindi-beaches" }, { label: "Malindi Old Town", path: "/attraction/malindi-old-town" }];
  return [];
}

function enrichStay(item) {
  return {
    ...item,
    relationship: item.relationship || "General accommodation",
    fullDescription: item.fullDescription || `${item.description} This is a destination guide and concierge introduction, not a verified booking listing.`,
    whatToExpect: item.whatToExpect || ["A conversation about your dates, group and preferred location", "Current property details, rates and availability confirmed through WhatsApp", "A flexible starting point with no online booking or payment on this site"],
    nearbyPlaces: item.nearbyPlaces || stayNearbyPlaces(item.location),
    planningLinks: item.planningLinks || stayPlanningLinks,
    imageCaption: item.imageCaption || "Confirm current accommodation details with Visit Malindi.",
  };
}

const foodPlanningLinks = [
  { label: "Places to stay", path: "/places-to-stay" },
  { label: "Things to do", path: "/things-to-do" },
  { label: "Excursions", path: "/excursions" },
  { label: "Nightlife", path: "/nightlife" },
  { label: "Transfers", path: "/transfers" },
  { label: "Itineraries", path: "/itineraries" },
];

const nightlifePlanningLinks = [
  { label: "Eat & drink", path: "/eat-and-drink" },
  { label: "Places to stay", path: "/places-to-stay" },
  { label: "Things to do", path: "/things-to-do" },
  { label: "Need transport tonight? Arrange with Visit Malindi.", path: "/transfers" },
  { label: "Itineraries", path: "/itineraries" },
  { label: "What's on", path: "/whats-on" },
];

function enrichFood(item) {
  return {
    ...item,
    fullDescription: item.fullDescription || `${item.description} Visit Malindi can pass on a table request and help shape the rest of your day or evening, while the venue confirms all current details.`,
    suitableFor: item.suitableFor || ["Couples", "Friends", "Families", "Independent travellers"],
    whatToExpect: item.whatToExpect || ["A table request handled manually through Visit Malindi", "Current menu, table availability and practical details confirmed before you go", "A food plan that can be paired with a stay, activity, transfer or night out"],
    usefulInfo: item.usefulInfo || ["Visit Malindi can send a reservation or table enquiry, but this is not an automated booking confirmation.", "Opening hours, menus, prices and table availability should be confirmed for your date."],
    nearbyPlaces: item.nearbyPlaces || defaultNearbyPlaces(item.location),
    planningLinks: item.planningLinks || foodPlanningLinks,
    imageCaption: item.imageCaption || "Illustrative dining image — confirm current venue details with Visit Malindi.",
  };
}

function enrichNightlife(item) {
  return {
    ...item,
    listingKind: item.listingKind || "Permanent venue",
    fullDescription: item.fullDescription || `${item.description} This is a permanent-venue guide, not a calendar of current events. Visit Malindi can help coordinate an evening around the latest local information.`,
    suitableFor: item.suitableFor || ["Couples", "Friends", "Groups", "Independent travellers"],
    whatToExpect: item.whatToExpect || ["Local guidance on where to go and how to shape the night", "Help pairing dinner, drinks, transport and group plans where available", "Live music, DJ sets and parties confirmed close to the time rather than presented as fixed events"],
    usefulInfo: item.usefulInfo || ["This page lists permanent venues. Current events, entry details, reservations and availability are confirmed through the concierge.", "Visit Malindi can help coordinate transport and local guidance where available; nothing here is an automated booking or event confirmation."],
    nearbyPlaces: item.nearbyPlaces || defaultNearbyPlaces(item.location),
    planningLinks: item.planningLinks || nightlifePlanningLinks,
    imageCaption: item.imageCaption || "Illustrative nightlife image — confirm current venue details with Visit Malindi.",
  };
}

const transferPlanningLinks = [
  { label: "Places to stay", path: "/places-to-stay" },
  { label: "Things to do", path: "/things-to-do" },
  { label: "Excursions", path: "/excursions" },
  { label: "Eat & drink", path: "/eat-and-drink" },
  { label: "Nightlife", path: "/nightlife" },
  { label: "Itineraries", path: "/itineraries" },
];

function enrichTransfer(item) {
  return {
    ...item,
    fullDescription: item.fullDescription || `${item.description} Visit Malindi receives your request on WhatsApp, then confirms the available options, price and practical arrangements manually.`,
    suitableFor: item.suitableFor || ["Couples", "Families", "Friends", "Groups", "Independent travellers"],
    whatToExpect: item.whatToExpect || ["A manual request based on your route, date, group and timing", "Current availability, price and practical arrangements confirmed through WhatsApp", "Help connecting your transfer with accommodation, activities, dining, nightlife or an itinerary where relevant"],
    usefulInfo: item.usefulInfo || ["Visit Malindi does not process automated bookings or payments for transfers.", "Share your route, date, number of passengers and pickup or arrival time so the concierge can confirm the current options.", "Vehicle, operator, availability, price and timing details are confirmed manually before any arrangements are made."],
    nearbyPlaces: item.nearbyPlaces || defaultNearbyPlaces(item.location),
    planningLinks: item.planningLinks || transferPlanningLinks,
    imageCaption: item.imageCaption || "Illustrative coast travel image — confirm current transfer details with Visit Malindi.",
    imageIsIllustrative: true,
  };
}

export const experiences = experienceEntries.map(enrichDiscoveryItem).map(withListingFields);
export const excursions = excursionEntries.map(enrichDiscoveryItem).map(withListingFields);
export const stays = stayEntries.map(enrichStay).map(withListingFields);
export const foodGuides = foodEntries.map(enrichFood).map(withListingFields);
export const nightlife = nightlifeEntries.map(enrichNightlife).map(withListingFields);
export const transfers = transferEntries.map(enrichTransfer).map(withListingFields);
export const attractions = attractionEntries.map(withListingFields);
export const itineraries = itineraryEntries.map(withListingFields);

// Keep this catalogue empty until current event details are supplied.
// Use this shape when adding time-sensitive event records.
export const eventTemplate = {
  id: "event-slug",
  slug: "event-slug",
  name: "Event name",
  venue: null,
  date: null,
  startTime: null,
  category: "Event",
  image: null,
  description: "Add a concise event description.",
  location: "Malindi",
  filters: [],
  expiresAt: null,
  highlights: [],
  usefulInfo: [],
  images: [],
  mapUrl: null,
  websiteUrl: null,
  socialUrl: null,
};
export const events = [];

export const searchIndex = [
  ...experiences.map((item) => ({ ...item, type: "Experience", path: `/experience/${item.slug}` })),
  ...excursions.map((item) => ({ ...item, type: "Excursion", path: `/excursion/${item.slug}` })),
  ...stays.map((item) => ({ ...item, type: "Stay", path: `/stay/${item.slug}` })),
  ...foodGuides.map((item) => ({ ...item, type: "Eat & Drink", path: `/eat-and-drink/${item.slug}` })),
  ...nightlife.map((item) => ({ ...item, type: "Nightlife", path: `/nightlife/${item.slug}` })),
  ...transfers.map((item) => ({ ...item, name: item.route, type: "Transfer", path: `/transfer/${item.slug}` })),
  ...attractions.map((item) => ({ ...item, type: "Place to Visit", path: `/attraction/${item.slug}` })),
  ...itineraries.map((item) => ({ ...item, type: "Itinerary", path: `/itinerary/${item.slug}` })),
  ...events.map((item) => ({ ...item, type: "Event", path: `/event/${item.slug}` })),
];

export const pageMeta = {
  "/": ["Visit Malindi — Discover the Coast Your Way.", "Your local guide to where to stay, what to do, where to eat and how to experience Malindi and the Kenyan Coast."],
  "/malindi": ["Malindi Travel Guide | Visit Malindi", "Plan a Malindi trip with a local guide to beaches, marine experiences, history, food, nightlife, transfers and itineraries."],
  "/watamu": ["Watamu Travel Guide | Visit Malindi", "Plan a Watamu trip with a local guide to beaches, marine experiences, Mida Creek, Gede Ruins, food, family days and transfers."],
  "/things-to-do": ["Things to Do in Malindi | Visit Malindi", "Explore marine, nature, culture and adventure experiences in Malindi and Watamu."],
  "/excursions": ["Excursions from Malindi | Visit Malindi", "Explore day trips and wider coast excursions from Malindi, Watamu and the Kenyan Coast."],
  "/places-to-stay": ["Places to Stay in Malindi | Visit Malindi", "Find the right base for your Malindi or Watamu trip, from beachfront stays to family-friendly options."],
  "/eat-and-drink": ["Eat & Drink in Malindi & Watamu | Visit Malindi", "Discover named restaurants, cafés, seafood, beach dining, bars and lounges, then ask Visit Malindi to make a table enquiry."],
  "/restaurants-in-malindi": ["Restaurants in Malindi | Visit Malindi", "Discover named Malindi restaurants, cafés, fine dining and beach dining, then ask Visit Malindi to make a table enquiry."],
  "/restaurants-in-watamu": ["Restaurants in Watamu | Visit Malindi", "Discover named Watamu restaurants, seafood, beach dining and lounges, then ask Visit Malindi to make a table enquiry."],
  "/nightlife": ["Nightlife in Malindi & Watamu | Visit Malindi", "Explore permanent coast venues, then ask Visit Malindi for tonight's local guidance, dinner plans, reservations and transport."],
  "/malindi-nightlife": ["Nightlife in Malindi | Visit Malindi", "Explore permanent Malindi venues and ask Visit Malindi to plan your night out, reservations and transport."],
  "/watamu-nightlife": ["Nightlife in Watamu | Visit Malindi", "Explore permanent Watamu venues and ask Visit Malindi to plan your night out, reservations and transport."],
  "/transfers": ["Malindi Transfers & Transport Concierge | Visit Malindi", "Request airport, SGR, intercity, local and experience transport through Visit Malindi on WhatsApp."],
  "/airport-transfers": ["Airport Transfers for Malindi & Watamu | Visit Malindi", "Request airport transport between Malindi or Mombasa Airport and Malindi or Watamu through the Visit Malindi concierge."],
  "/sgr-transfers": ["Mombasa SGR Transfers | Visit Malindi", "Request a connection between Mombasa SGR and Malindi or Watamu through the Visit Malindi concierge."],
  "/intercity-transfers": ["Intercity Transfers on the Kenyan Coast | Visit Malindi", "Request travel between Malindi, Watamu, Kilifi, Mombasa, Mambrui and Lamu through Visit Malindi."],
  "/local-transfers": ["Local & Experience Transfers | Visit Malindi", "Request hotel, restaurant, excursion, nightlife, airport, day-trip or group transport through Visit Malindi."],
  "/places-to-visit": ["Places to Visit in Malindi | Visit Malindi", "Beaches, history, nature and culture across Malindi, Watamu and the Kenyan Coast."],
  "/itineraries": ["Malindi Itineraries | Visit Malindi", "Ready-made ideas for one day, three days, a weekend, a family holiday or a honeymoon."],
  "/whats-on": ["What's On in Malindi | Visit Malindi", "Find out what is happening in Malindi tonight and this weekend."],
};

const sharedDestinationNav = [
  { label: "Things to do", path: "/things-to-do" },
  { label: "Excursions", path: "/excursions" },
  { label: "Places to visit", path: "/places-to-visit" },
  { label: "Stay", path: "/places-to-stay" },
  { label: "Eat & drink", path: "/eat-and-drink" },
  { label: "Nightlife", path: "/nightlife" },
  { label: "Transfers", path: "/transfers" },
  { label: "Itineraries", path: "/itineraries" },
  { label: "What's on", path: "/whats-on" },
];

export const destinations = {
  malindi: {
    name: "Malindi",
    slug: "malindi",
    mark: "ML",
    eyebrow: "Destination guide · Kenya's coast",
    title: "Malindi, your way.",
    intro: "A warm-water coast town with marine experiences, layered Swahili and Portuguese history, easy beach days and a local rhythm that rewards taking your time.",
    image: photos.hero,
    imageAlt: "Indian Ocean shoreline along the Kenyan Coast",
    navLinks: sharedDestinationNav,
    whyVisit: {
      title: "Come for the ocean. Stay for the layers.",
      text: "Malindi brings together a waterfront, marine experiences, beaches, old-town history and access to the wider coast. It works for a slow weekend, a family base, a couple's escape or a longer trip built around the sea."
    },
    focusText: "Use this guide to move from the big picture to the details that shape a good day: what to do, where to go, how to move between places and what to ask before you make arrangements.",
    focusCards: [
      { title: "What to do", text: "Marine, beach, nature, culture and easy coast days.", path: "/things-to-do-in-malindi" },
      { title: "Places to visit", text: "Waterfront landmarks, beaches and history close to town.", path: "/places-to-visit" },
      { title: "Plan an escape", text: "A day, a weekend or a Malindi + Watamu route.", path: "/itineraries" },
      { title: "Ask a local", text: "Get help choosing the right pace for your trip.", path: "/contact" },
    ],
    sections: [
      { id: "what-to-do", eyebrow: "Start here", title: "What to do in Malindi", text: "Build the day around the Indian Ocean, then add the kind of detail that makes the trip feel like yours.", links: [
        { title: "Things to do in Malindi", text: "Browse marine, beach, nature, family and culture-led ideas.", path: "/things-to-do-in-malindi" },
        { title: "Marine experiences", text: "Snorkelling, diving, dhow sailing and time on the water.", path: "/experience/malindi-marine-national-park" },
        { title: "Malindi itineraries", text: "Use a day, three days or a weekend as a starting point.", path: "/itineraries" },
      ] },
      { id: "places", eyebrow: "See the place", title: "Places to visit", text: "Malindi is easy to explore in pieces: a waterfront landmark, a historic stop, a beach and a little time away from the centre.", links: [
        { title: "Places to Visit", text: "Browse the wider catalogue of beaches, history and nature.", path: "/places-to-visit" },
        { title: "Vasco da Gama Pillar", text: "A waterfront landmark to include in a slower town walk.", path: "/attraction/vasco-da-gama-pillar" },
        { title: "Malindi Old Town", text: "Take in layers of coastal history, culture and everyday life.", path: "/attraction/malindi-old-town" },
        { title: "Malindi Museum", text: "Add context to the town's coastal history.", path: "/attraction/malindi-museum" },
      ] },
      { id: "beaches", eyebrow: "By the water", title: "Beaches in Malindi", text: "Choose between a simple beach day, a quieter shoreline or a base for marine activities. Confirm current conditions and access locally.", links: [
        { title: "Malindi beaches", text: "Start with the coast closest to the town's rhythm.", path: "/attraction/malindi-beaches" },
        { title: "Silversands", text: "A quieter setting for a beach-led day.", path: "/attraction/silversands" },
        { title: "Casuarina", text: "Explore the Casuarina side at your own pace.", path: "/attraction/casuarina" },
        { title: "Beach activities", text: "Find ideas for making the shoreline part of the day.", path: "/experience/beach-activities" },
      ] },
      { id: "marine", eyebrow: "Indian Ocean", title: "Marine experiences", text: "The water is central to Malindi. Ask about current conditions, responsible practice, timing and the best fit for your group.", links: [
        { title: "Malindi Marine National Park", text: "A starting point for marine time from Malindi.", path: "/experience/malindi-marine-national-park" },
        { title: "Snorkelling on the coast", text: "A simple way to spend time in the water.", path: "/experience/snorkelling-on-the-coast" },
        { title: "Diving on the coast", text: "Ask about current diving possibilities.", path: "/experience/diving-on-the-coast" },
        { title: "Dhow sailing", text: "See the coastline from a traditional dhow.", path: "/experience/dhow-sailing" },
      ] },
      { id: "food", eyebrow: "Taste the coast", title: "Food and dining", text: "Plan around seafood, Swahili flavours, café mornings, beach dining or a more considered evening. The guide stays at category level so the concierge can confirm what is current.", links: [
        { title: "Eat & Drink", text: "Browse the wider guide to restaurants, cafés, seafood and bars.", path: "/eat-and-drink" },
        { title: "Restaurants in Malindi", text: "Start with a local food and dining enquiry.", path: "/restaurants-in-malindi" },
        { title: "Ask for a food plan", text: "Share your mood, budget and location with the concierge.", path: "/contact" },
      ] },
      { id: "nightlife", eyebrow: "After dark", title: "Nightlife in Malindi", text: "Evenings can mean a beach lounge, live music, a DJ or simply dinner by the water. What is happening changes, so ask close to the time.", links: [
        { title: "Nightlife in Malindi", text: "Browse the nightlife guide and category-level options.", path: "/malindi-nightlife" },
        { title: "What's On", text: "Ask what is happening tonight or this weekend.", path: "/whats-on" },
      ] },
      { id: "family", eyebrow: "For all ages", title: "Family activities", text: "Keep the schedule flexible: easy beach time, short marine experiences, nature and food stops can all fit without making the day feel rushed.", links: [
        { title: "Family activities", text: "Find family-friendly coast ideas.", path: "/experience/family-coast-day" },
        { title: "Family holiday itinerary", text: "A flexible starting point for a family trip.", path: "/itinerary/family-holiday" },
        { title: "Plan around your group", text: "Ask the concierge about timing and current options.", path: "/plan-my-trip" },
      ] },
      { id: "couples", eyebrow: "For two", title: "Couples and romantic experiences", text: "Give the trip room for a sunset, a slow meal, an ocean experience or a day with no fixed agenda.", links: [
        { title: "Couples experiences", text: "Browse romantic and unhurried coast ideas.", path: "/experience/couples-coast-day" },
        { title: "Honeymoon by the Coast", text: "A flexible itinerary for a special trip.", path: "/itinerary/honeymoon" },
        { title: "Couple's getaway", text: "Balance beach time, food and adventure.", path: "/itinerary/couples-getaway" },
      ] },
      { id: "nature-culture", eyebrow: "Beyond the beach", title: "Nature, culture and history", text: "Malindi's character comes from the meeting of coast, history and living culture. Take a slower route through town, then look outward to the river, forest and nearby heritage sites.", links: [
        { title: "Portuguese Chapel", text: "A historic place to include in an old-town walk.", path: "/attraction/portuguese-chapel" },
        { title: "Sabaki River", text: "A wider-coast nature destination to consider.", path: "/attraction/sabaki-river" },
        { title: "Gede and Arabuko Sokoke", text: "Combine heritage and coastal forest in one excursion.", path: "/excursion/gede-and-arabuko-sokoke" },
        { title: "Wildlife on the coast", text: "Add a nature-led idea to your plans.", path: "/experience/wildlife-on-the-coast" },
      ] },
    ],
    practicalIntro: "Whether you arrive by air, train or road, the easiest next step is to share your arrival details and destination with the concierge so the current options can be confirmed.",
    practical: [
      { title: "Getting around", text: "Ask about private coastal transfers and moving between Malindi, Watamu and nearby destinations.", path: "/transfers" },
      { title: "Malindi Airport", text: "Arrange the airport-to-Malindi leg around your arrival time.", path: "/transfer/malindi-airport-to-malindi" },
      { title: "Mombasa Airport", text: "Plan the road connection from Mombasa Airport to Malindi.", path: "/transfer/mombasa-airport-to-malindi" },
      { title: "SGR connection", text: "Continue from Mombasa SGR to Malindi by arranging the onward leg.", path: "/transfer/sgr-to-malindi" },
    ],
    nearbyText: "Malindi is a useful base for seeing more of the coast. Ask about timing and current travel options before setting a day-trip plan.",
    nearby: [
      { title: "Watamu and Mida Creek", text: "Move north for beaches, marine experiences and mangrove waterways.", path: "/excursion/watamu-and-mida-creek" },
      { title: "Mambrui", text: "Add a wider-coast stop north of Malindi.", path: "/excursion/mambrui-excursion" },
      { title: "Kilifi", text: "Shape a longer coast route south of Malindi.", path: "/excursion/kilifi-excursion" },
      { title: "Marafa / Hell's Kitchen", text: "Consider an inland landscape excursion.", path: "/excursion/marafa-hells-kitchen" },
    ],
    itineraryText: "There is no single right pace. Use a ready-made idea to make the first decision, then message the concierge to adjust it around your arrival, interests and energy.",
    itineraries: [
      { title: "1 Day in Malindi", text: "A compact taste of ocean, history and sunset.", path: "/itinerary/1-day-in-malindi" },
      { title: "3 Days in Malindi", text: "Make room for marine time, culture, food and slow mornings.", path: "/itinerary/3-days-in-malindi" },
      { title: "Malindi + Watamu", text: "See two different sides of the coast.", path: "/itinerary/malindi-and-watamu" },
    ],
  },
  watamu: {
    name: "Watamu",
    slug: "watamu",
    mark: "WT",
    eyebrow: "Destination guide · Kenya's coast",
    title: "Watamu, close to the water.",
    intro: "A coastal base for beach time, marine experiences, Mida Creek's mangrove waterways, nearby Gede heritage and nature-led days at an easy pace.",
    image: photos.midaCreek,
    imageAlt: "Mangrove-lined waters in Mida Creek near Watamu",
    navLinks: sharedDestinationNav,
    whyVisit: {
      title: "Come for the beaches. Stay for the living coast.",
      text: "Watamu gives a trip a water-first rhythm, with beaches, marine experiences, Mida Creek and access to Gede Ruins and Arabuko Sokoke. It suits families, couples, nature-led travellers and anyone who wants to keep the day open."
    },
    focusText: "Start with the water, then choose how far you want to go: a beach morning, a marine experience, a mangrove sunset, a heritage stop or a longer day across the coast.",
    focusCards: [
      { title: "What to do", text: "Marine, mangrove, nature, family and beach ideas.", path: "/things-to-do-in-watamu" },
      { title: "Mida Creek", text: "Mangrove waterways and wide tidal horizons.", path: "/attraction/mida-creek" },
      { title: "Gede and Arabuko", text: "Heritage and coastal forest close to Watamu.", path: "/excursion/gede-and-arabuko-sokoke" },
      { title: "Ask a local", text: "Get help shaping a Watamu-first trip.", path: "/contact" },
    ],
    sections: [
      { id: "what-to-do", eyebrow: "Start here", title: "What to do in Watamu", text: "Keep the day simple or build it around the water, wildlife, mangroves, heritage and the nearby coast.", links: [
        { title: "Things to do in Watamu", text: "Browse water, nature, family and culture-led ideas.", path: "/things-to-do-in-watamu" },
        { title: "Mida Creek", text: "Slow down among mangroves and tidal horizons.", path: "/experience/mida-creek-sunset" },
        { title: "Watamu excursions", text: "Use the wider excursion catalogue to shape a day out.", path: "/excursions" },
      ] },
      { id: "places", eyebrow: "See the place", title: "Places to visit", text: "Watamu's strongest days often combine a beach or marine stop with somewhere that gives the coast more context.", links: [
        { title: "Watamu beaches", text: "Start with an easy shoreline day.", path: "/attraction/watamu-beaches" },
        { title: "Watamu Marine National Park", text: "A marine destination to build into your plans.", path: "/attraction/watamu-marine-national-park" },
        { title: "Gede Ruins", text: "Historic Swahili settlement remains near the coastal forest.", path: "/attraction/gede-ruins" },
        { title: "Places to Visit", text: "Browse the wider guide to the Kenyan Coast.", path: "/places-to-visit" },
      ] },
      { id: "beaches", eyebrow: "By the water", title: "Beaches in Watamu", text: "Use the beach as your anchor, then decide whether the day needs a marine activity, a nature stop or nothing else at all.", links: [
        { title: "Watamu beaches", text: "A starting point for choosing your shoreline pace.", path: "/attraction/watamu-beaches" },
        { title: "Beach activities", text: "Add easy activities for friends or family.", path: "/experience/beach-activities" },
        { title: "Water sports", text: "Ask about current options on the Watamu coast.", path: "/experience/water-sports" },
      ] },
      { id: "marine", eyebrow: "Indian Ocean", title: "Marine experiences", text: "Watamu's water is a central part of the destination. Confirm current conditions, responsible wildlife practice and the right timing before you go.", links: [
        { title: "Watamu Marine National Park", text: "Explore the Watamu side of the marine coast.", path: "/experience/watamu-marine-national-park" },
        { title: "Snorkelling on the coast", text: "Spend time in the water with local guidance.", path: "/experience/snorkelling-on-the-coast" },
        { title: "Dolphin experiences", text: "Ask about responsible experiences and conditions.", path: "/experience/dolphin-experiences" },
        { title: "Turtle-related experiences", text: "Ask about current, responsible ways to include turtles.", path: "/experience/turtle-related-experiences" },
      ] },
      { id: "food", eyebrow: "Taste the coast", title: "Food and dining", text: "Keep meals relaxed: seafood, Swahili flavours, café mornings, casual dining and beach-led evenings all fit the Watamu pace.", links: [
        { title: "Eat & Drink", text: "Browse the wider guide to food, cafés, seafood and bars.", path: "/eat-and-drink" },
        { title: "Food by the water", text: "Ask for current category-level recommendations.", path: "/contact" },
        { title: "Plan a dining day", text: "Tell the concierge what kind of table you want.", path: "/plan-my-trip" },
      ] },
      { id: "nightlife", eyebrow: "After dark", title: "Nightlife around Watamu", text: "Nightlife is best treated as a live question: ask what is happening while you are there and whether the evening is better suited to a lounge, music or a beach-led plan.", links: [
        { title: "Nightlife", text: "Browse current nightlife categories across the coast.", path: "/nightlife" },
        { title: "What's On", text: "Ask about tonight, this weekend or your travel dates.", path: "/whats-on" },
      ] },
      { id: "family", eyebrow: "For all ages", title: "Family activities", text: "Watamu works well when the schedule leaves space for breaks: beach time, short marine activities, Mida Creek and nature can be mixed at an easy pace.", links: [
        { title: "Family coast day", text: "A flexible starting point for a family day.", path: "/experience/family-coast-day" },
        { title: "Family holiday", text: "Build a beach, nature and food-led trip.", path: "/itinerary/family-holiday" },
        { title: "Plan around your group", text: "Ask about current timing and suitable options.", path: "/plan-my-trip" },
      ] },
      { id: "couples", eyebrow: "For two", title: "Couples and romantic experiences", text: "Leave room for a quiet beach, a sunset around Mida Creek, a marine experience or an unhurried meal.", links: [
        { title: "Couples experiences", text: "Find romantic and slow-paced coast ideas.", path: "/experience/couples-coast-day" },
        { title: "Couple's getaway", text: "A flexible framework for two.", path: "/itinerary/couples-getaway" },
        { title: "Honeymoon by the Coast", text: "Shape a special trip around unhurried days.", path: "/itinerary/honeymoon" },
      ] },
      { id: "nature-culture", eyebrow: "Beyond the beach", title: "Nature, culture and history", text: "Watamu's destination story reaches inland and outward: mangroves, coastal forest and the remains of Gede add depth to a beach-first trip.", links: [
        { title: "Mida Creek", text: "Explore a mangrove-lined coastal creek.", path: "/attraction/mida-creek" },
        { title: "Gede Ruins", text: "Add Swahili heritage to the day.", path: "/attraction/gede-ruins" },
        { title: "Arabuko Sokoke Forest", text: "Consider forest and nature beyond the beach.", path: "/attraction/arabuko-sokoke-forest" },
        { title: "Gede and Arabuko Sokoke", text: "Combine heritage and forest in one excursion.", path: "/excursion/gede-and-arabuko-sokoke" },
      ] },
    ],
    practicalIntro: "Watamu is connected by road to Malindi and the wider coast. Share where you are arriving from and where you are staying so the current transfer options can be confirmed.",
    practical: [
      { title: "Getting around", text: "Arrange the coast legs between Watamu, Malindi and nearby destinations.", path: "/transfers" },
      { title: "Mombasa Airport", text: "Plan the road connection from Mombasa Airport to Watamu.", path: "/transfer/mombasa-airport-to-watamu" },
      { title: "Malindi connection", text: "Ask about the road connection between Malindi and Watamu.", path: "/transfer/malindi-to-watamu" },
      { title: "SGR connection", text: "Continue from Mombasa SGR to Watamu by road.", path: "/transfer/mombasa-sgr-to-watamu" },
    ],
    nearbyText: "Watamu sits well for coast days in either direction. Use the concierge to check timing and shape the route around what you want to see.",
    nearby: [
      { title: "Malindi", text: "Head south for waterfront history, beaches and marine experiences.", path: "/excursion/malindi-coast-excursion" },
      { title: "Mambrui", text: "Add a wider-coast stop north of Malindi.", path: "/excursion/mambrui-excursion" },
      { title: "Kilifi", text: "Shape a longer route south along the coast.", path: "/excursion/kilifi-excursion" },
      { title: "Mombasa", text: "Consider a longer coastal city connection.", path: "/excursion/mombasa-day-trip" },
    ],
    itineraryText: "Start with the part of Watamu you are most excited about, then use the rest of the plan to protect time for the water and the people you are travelling with.",
    itineraries: [
      { title: "Malindi + Watamu", text: "See both destinations without rushing the coast.", path: "/itinerary/malindi-and-watamu" },
      { title: "Family Holiday", text: "Keep beach, nature and food flexible.", path: "/itinerary/family-holiday" },
      { title: "Couple's Getaway", text: "Balance beach time, food and adventure.", path: "/itinerary/couples-getaway" },
    ],
  },
};

export { photos };